version: "3.9"
services:
  db:
    tty: true
    stdin_open: true
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
      PGDATA: /var/lib/postgresql/data/devcontainerGuidelinesPgData
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./db/logs:/var/log
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  batch:
    # tty: true
    # stdin_open: true
    image: node:17.9
    # command: nodemon -L --inspect=0.0.0.0:5859
    # ports:
    #   - 5858:5858
  backend:
    tty: true
    stdin_open: true
    image: node:17.9
    working_dir: /workspace/backend
    command: bash -c "npm install && cp .env.sample .env && npx prisma migrate deploy && npm run nodemon"
    ports:
      - 3000:3000
    volumes:
      - .:/workspace
    depends_on:
      - frontend
      - db

  frontend:
    tty: true
    stdin_open: true
    image: node:17.9
    working_dir: /workspace/frontend
    command: bash -c "npm install && PORT=4000 npm start"
    ports:
      - 4000:4000
    volumes:
      - .:/workspace
